project_id: CROWDIN_PAIMON_PROJECT_ID
api_token_env: CROWDIN_PAIMON_PERSONAL_TOKEN
base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: 1
files:
  - source: /_locales/en_US/messages.json
    translation: /_locales/%locale_with_underscore%/messages.json
